exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.10.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.1
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    exclude: tests/data
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'keyring==24.2.0',
        'nox==2024.03.02',
        'pytest',
        'types-docutils==0.20.0.3',
        'types-setuptools==68.2.0.0',
        'types-freezegun==1.1.10',
        'types-pyyaml==6.0.12.12',
    ]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]
    exclude: NEWS.rst  # The errors flagged in NEWS.rst are old.

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
    - id: codespell
      exclude: AUTHORS.txt|tests/data
      args: ["--ignore-words", tools/codespell-ignore.txt]

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(process|removal|feature|bugfix|vendor|doc|trivial).rst
    exclude: ^news/(.gitignore|.*\.(process|removal|feature|bugfix|vendor|doc|trivial).rst)
    files: ^news/

ci:
  autofix_prs: false
  autoupdate_commit_msg: 'pre-commit autoupdate'
  autoupdate_schedule: monthly
