exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    exclude: |
      (?x)
        ^docs/|
        ^src/pip/_internal/cli|
        ^src/pip/_internal/commands|
        ^src/pip/_internal/distributions|
        ^src/pip/_internal/index|
        ^src/pip/_internal/models|
        ^src/pip/_internal/network|
        ^src/pip/_internal/operations|
        ^src/pip/_internal/req|
        ^src/pip/_internal/resolution|
        ^src/pip/_internal/utils|
        ^src/pip/_internal/vcs|
        ^src/pip/_internal/\w+\.py$|
        ^src/pip/__main__.py$|
        ^tools/|
        # Tests
        ^tests/conftest.py|
        ^tests/yaml|
        ^tests/lib|
        ^tests/data|
        ^tests/unit|
        ^tests/functional/(?!test_install)|
        ^tests/functional/test_install|
        # Files in the root of the repository
        ^setup.py|
        ^noxfile.py|
        # A blank ignore, to avoid merge conflicts later.
        ^$


- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies: [
        'flake8-bugbear==20.1.4',
        'flake8-logging-format==0.6.0',
    ]
    exclude: tests/data

- repo: https://github.com/PyCQA/isort
  rev: 5.5.3
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    exclude: docs|tests
    args: ["--pretty"]
  - id: mypy
    name: mypy, for Python 2
    exclude: noxfile.py|tools/automation/release|docs|tests
    args: ["--pretty", "-2"]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.6.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]
    exclude: NEWS.rst  # The errors flagged in NEWS.rst are old.

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(process|removal|feature|bugfix|vendor|doc|trivial).rst
    exclude: ^news/(.gitignore|.*\.(process|removal|feature|bugfix|vendor|doc|trivial).rst)
    files: ^news/

- repo: https://github.com/mgedmin/check-manifest
  rev: '0.43'
  hooks:
  - id: check-manifest
