exclude: 'src/pip/_vendor/'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: WHEEL
  - id: forbid-new-submodules
  - id: trailing-whitespace
    exclude: .patch

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.270
  hooks:
    - id: ruff

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
  - id: mypy
    exclude: tests/data
    args: ["--pretty", "--show-error-codes"]
    additional_dependencies: [
        'keyring==23.0.1',
        'nox==2021.6.12',
        'pytest',
        'types-docutils==0.18.3',
        'types-setuptools==57.4.14',
        'types-freezegun==1.1.9',
        'types-six==1.16.15',
        'types-pyyaml==6.0.12.2',
    ]

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-no-log-warn
  - id: python-no-eval
  - id: rst-backticks
    files: .*\.rst$
    types: [file]
    exclude: NEWS.rst  # The errors flagged in NEWS.rst are old.

- repo: local
  hooks:
  - id: news-fragment-filenames
    name: NEWS fragment
    language: fail
    entry: NEWS fragment files must be named *.(process|removal|feature|bugfix|vendor|doc|trivial).rst
    exclude: ^news/(.gitignore|.*\.(process|removal|feature|bugfix|vendor|doc|trivial).rst)
    files: ^news/

ci:
  autofix_prs: false
  autoupdate_commit_msg: 'pre-commit autoupdate'
  autoupdate_schedule: monthly
