language: python
cache: pip
dist: xenial
python: 3.8
addons:
  apt:
    packages:
    - bzr

stages:
- primary
- secondary
- experimental

jobs:
  include:
    # Basic Checks
    # - stage: primary
    #   env: TOXENV=docs
    # - env: TOXENV=lint
    # - env: TOXENV=vendoring

    # # Complete checking for ensuring compatibility
    # # PyPy
    # - stage: secondary
    #   env: GROUP=1
    #   python: pypy3.5-7.0.0
    # - env: GROUP=2
    #   python: pypy3.5-7.0.0
    # - env: GROUP=1
    #   python: pypy2.7-7.1.1
    # - env: GROUP=2
    #   python: pypy2.7-7.1.1

    # Test experimental stuff that are not part of the standard pip usage.
    # Helpful for developers working on them to see how they're doing.
    - stage: experimental
      env:
      - GROUP=1
      - NEW_RESOLVER=1
    - env:
      - GROUP=2
      - NEW_RESOLVER=1
    - env:
      - GROUP=3
      - NEW_RESOLVER=1

  fast_finish: true
  allow_failures:
    - env: GROUP=3 NEW_RESOLVER=1

before_install: tools/travis/setup.sh
install: travis_retry tools/travis/install.sh
script: tools/travis/run.sh

notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The actual value here is: irc.freenode.org#pypa-dev
      - secure: zAlwcmrDThlRsZz7CPDGpj4ABTzf7bc/zQXYtvIuqmSj0yJMAwsO5Vx/+qdTGYBvmW/oHw2s/uUgtkZzntSQiVQToKMag2fs0d3wV5bLJQUE2Si2jnH2JOQo3JZWSo9HOqL6WYmlKGI8lH9FVTdVLgpeJmIpLy1bN4zx4/TiJjc=
    skip_join: true
    use_notice: true
