language: python

env:
  - TOXENV=docs
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=pypy

install:
  - sudo apt-get install subversion bzr mercurial
  - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
  - git config --global user.email "python-virtualenv@googlegroups.com"
  - git config --global user.name "Pip"
  - pip install tox

script: tox

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X

notifications:
  irc: "irc.freenode.org#pip"
