language: python
sudo: false
cache: pip
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: TOXENV=docs
    - env: TOXENV=lint-py2
    - env: TOXENV=lint-py3
    - env: TOXENV=mypy
    - env: TOXENV=packaging
    # PyPy jobs start first -- they are the slowest
    - env: TOXENV=pypy3-functional-install
      python: pypy3
    - env: TOXENV=pypy3-functional
      python: pypy3
    - env: TOXENV=pypy-functional-install
      python: pypy
    - env: TOXENV=pypy-functional
      python: pypy
    # Latest Stable CPython jobs
    - env: TOXENV=py27-functional-install
      python: 2.7
    - env: TOXENV=py27-functional
      python: 2.7
    - env: TOXENV=py36-functional-install
      python: 3.6
    - env: TOXENV=py36-functional
      python: 3.6
    # All the other Py3 versions
    - env: TOXENV=py35-functional-install
      python: 3.5
    - env: TOXENV=py35-functional
      python: 3.5
    - env: TOXENV=py34-functional-install
      python: 3.4
    - env: TOXENV=py34-functional
      python: 3.4
    # Fast unit tests near the end
    - env: TOXENV=pypy3-unit
      python: pypy3
    - env: TOXENV=pypy-unit
      python: pypy
    - env: TOXENV=py27-unit
      python: 2.7
    - env: TOXENV=py36-unit
      python: 3.6
    - env: TOXENV=py35-unit
      python: 3.5
    - env: TOXENV=py34-unit
      python: 3.4
    # Nightly Python goes last
    - env: TOXENV=py37-functional-install
      python: nightly
    - env: TOXENV=py37-functional
      python: nightly
    - env: TOXENV=py37-unit
      python: nightly
  allow_failures:
    - python: nightly

install: travis_retry .travis/install.sh
script: .travis/run.sh

notifications:
  irc:
    channels:
      # This is set to a secure variable to prevent forks from notifying the
      # IRC channel whenever they fail a build. This can be removed when travis
      # implements https://github.com/travis-ci/travis-ci/issues/1094.
      # The actual value here is: irc.freenode.org#pypa-dev
      - secure: zAlwcmrDThlRsZz7CPDGpj4ABTzf7bc/zQXYtvIuqmSj0yJMAwsO5Vx/+qdTGYBvmW/oHw2s/uUgtkZzntSQiVQToKMag2fs0d3wV5bLJQUE2Si2jnH2JOQo3JZWSo9HOqL6WYmlKGI8lH9FVTdVLgpeJmIpLy1bN4zx4/TiJjc=
    skip_join: true
    use_notice: true
