language: python
cache: pip
dist: xenial
python: 3.9
addons:
  apt:
    packages:
    - bzr

stages:
- primary
- secondary

jobs:
  include:
    # Basic Checks
    - stage: primary
      env: TOXENV=docs
    - env: TOXENV=lint
    - env: TOXENV=vendoring

    # Complete checking for ensuring compatibility
    # PyPy
    - stage: secondary
      env: GROUP=1
      python: pypy3.5-7.0.0
    - env: GROUP=2
      python: pypy3.5-7.0.0
    - env: GROUP=1
      python: pypy2.7-7.1.1
    - env: GROUP=2
      python: pypy2.7-7.1.1

before_install: tools/travis/setup.sh
install: travis_retry tools/travis/install.sh
script: tools/travis/run.sh
