language: python

env:
  - TOXENV=pep8
  - TOXENV=py3pep8
  - TOXENV=docs
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

before_install:
  - "[ -d ~/.distlib ] && sudo chown -R travis:travis ~/.distlib || true"

install:
  - "if [[ $TOXENV == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa; fi"
  - "if [[ $TOXENV == 'pypy' ]]; then sudo apt-get -y update && sudo apt-get -y install pypy; fi"
  # This is required because we need to get rid of the Travis installed PyPy
  # or it'll take precedence over the PPA installed one.
  - "if [[ $TOXENV == 'pypy' ]]; then sudo rm -rf /usr/local/pypy/bin; fi"
  - "if [[ $TOXENV == 'py34' ]]; then .travis/py34.sh; fi"
  - sudo apt-get install subversion bzr mercurial
  - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
  - git config --global user.email "python-virtualenv@googlegroups.com"
  - git config --global user.name "Pip"
  - pip install --upgrade setuptools
  - pip install tox

script: tox

branches:
  only:
    - develop
    - 1.3.X
    - 1.4.X
    - 1.5.X

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
