language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
before_install:
    - sudo apt-get install subversion bzr mercurial
    - echo -e "[web]\ncacerts = /etc/ssl/certs/ca-certificates.crt" >> ~/.hgrc
install: pip install nose virtualenv scripttest mock
script: nosetests
notifications:
branches:
  only:
    - wheel_install
env:
  - PIP_USE_MIRRORS=true
