# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
- name: ðŸ’¬ Discourse
  url: https://discuss.python.org/c/packaging
  about: |
    Please ask typical Q&A here: general ideas for Python packaging,
    questions about structuring projects and so on
- name: 'ðŸ’¬ IRC: #pypa'
  url: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat:+6697/pypa
  about: Chat with devs
