# Documentation for this file can be found at:
# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ IRC: #pypa"
    url: https://kiwiirc.com/nextclient/#ircs://irc.libera.chat:+6697/pypa
    about: Chat with devs
