name: Code quality

on:
  push:
  pull_request:
  schedule:
  # Run every Friday at 18:02 UTC
  # https://crontab.guru/#2_18_*_*_5
  - cron: 2 18 * * 5

jobs:
  linters:
    name: ðŸ¤–
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 5
      matrix:
        os:
        - ubuntu-18.04
        env:
        - TOXENV: docs
        - TOXENV: lint
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.env.PYTHON_VERSION || 3.7 }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.env.PYTHON_VERSION || 3.7 }}
    - name: Pre-configure global Git settings
      run: >-
        tools/travis/setup.sh
    - name: Update setuptools and tox dependencies
      run: >-
        tools/travis/install.sh
    - name: 'Initialize tox envs: ${{ matrix.env.TOXENV }}'
      run: >-
        python -m tox --notest --skip-missing-interpreters false
      env: ${{ matrix.env }}
    - name: Test with tox
      run: >-
        python -m tox
      env: ${{ matrix.env }}
